//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUEVOSFESTIVAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALANCERUTA
    {
        public int ID { get; set; }
        public int EXTR { get; set; }
        public int AAR { get; set; }
        public int AR { get; set; }
        public int BR { get; set; }
        public int EXTB { get; set; }
        public int AAB { get; set; }
        public int AB { get; set; }
        public int BB { get; set; }
        public int IDUSUARIO { get; set; }
        public int IDCARRO { get; set; }
        public double VENTASCONTADO { get; set; }
        public double VENTASCREDITO { get; set; }
        public double ABONOS { get; set; }
        public System.DateTime FECHA { get; set; }
        public int DEXTR { get; set; }
        public int DAAR { get; set; }
        public int DAR { get; set; }
        public int DBR { get; set; }
        public int DEXTB { get; set; }
        public int DAAB { get; set; }
        public int DAB { get; set; }
        public int DBB { get; set; }
        public double MONTOEFECTIVO { get; set; }
        public int IDCARGA { get; set; }
        public double DIFERENCIA { get; set; }
    
        public virtual CARGUE CARGUE { get; set; }
        public virtual CARROS CARROS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
