//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUEVOSFESTIVAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGUE2
    {
        public int IDCARGA2 { get; set; }
        public int EXTR { get; set; }
        public int AAR { get; set; }
        public int AR { get; set; }
        public int BR { get; set; }
        public int EXTB { get; set; }
        public int AAB { get; set; }
        public int AB { get; set; }
        public int BB { get; set; }
        public int IDUSUARIO { get; set; }
        public int IDCARRO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public int IDCARGA { get; set; }
    
        public virtual CARGUE CARGUE { get; set; }
        public virtual CARROS CARROS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
