//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUEVOSFESTIVAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGUE()
        {
            this.BALANCERUTA = new HashSet<BALANCERUTA>();
            this.CAMBIOS = new HashSet<CAMBIOS>();
            this.CARGUE2 = new HashSet<CARGUE2>();
            this.VENTA_PRODWEB = new HashSet<VENTA_PRODWEB>();
        }
    
        public int IDCARGA { get; set; }
        public int EXTR { get; set; }
        public int AAR { get; set; }
        public int AR { get; set; }
        public int BR { get; set; }
        public int EXTB { get; set; }
        public int AAB { get; set; }
        public int AB { get; set; }
        public int BB { get; set; }
        public int IDUSUARIO { get; set; }
        public int IDCARRO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALANCERUTA> BALANCERUTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMBIOS> CAMBIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGUE2> CARGUE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_PRODWEB> VENTA_PRODWEB { get; set; }
        public virtual CARROS CARROS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
