//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUEVOSFESTIVAL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FESTIVALEntities : DbContext
    {
        public FESTIVALEntities()
            : base("name=FESTIVALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONOSCOMPRASCREDITO> ABONOSCOMPRASCREDITO { get; set; }
        public virtual DbSet<ABONOSVENTASCREDITO> ABONOSVENTASCREDITO { get; set; }
        public virtual DbSet<BALANCERUTA> BALANCERUTA { get; set; }
        public virtual DbSet<CAMBIOS> CAMBIOS { get; set; }
        public virtual DbSet<CARGUE> CARGUE { get; set; }
        public virtual DbSet<CARGUE2> CARGUE2 { get; set; }
        public virtual DbSet<CARROS> CARROS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPRAS> COMPRAS { get; set; }
        public virtual DbSet<CONSECUTIVO> CONSECUTIVO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public virtual DbSet<REFERENCIAS> REFERENCIAS { get; set; }
        public virtual DbSet<RUTA> RUTA { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_TIPO> Tbl_TIPO { get; set; }
        public virtual DbSet<TIPOUSUARIOREGISTRO> TIPOUSUARIOREGISTRO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<VENTA_PROD> VENTA_PROD { get; set; }
        public virtual DbSet<VENTA_PRODWEB> VENTA_PRODWEB { get; set; }
        public virtual DbSet<VENTASCREDITO> VENTASCREDITO { get; set; }
        public virtual DbSet<COMPRASCREDITO> COMPRASCREDITO { get; set; }
        public virtual DbSet<DEVCOMPRAS> DEVCOMPRAS { get; set; }
        public virtual DbSet<DEVENTA_PROD> DEVENTA_PROD { get; set; }
        public virtual DbSet<GASTOS> GASTOS { get; set; }
        public virtual DbSet<LIBRODIARIO> LIBRODIARIO { get; set; }
    }
}
